server:
  port: 10086   #服务端口
spring:
  application:
    name: eureka-server   #eureka服务名称
eureka:
  client:
    service-url:          #eureka的地址信息，自己也是一个微服务，把自己也注册上去
      defaultZone: http://127.0.0.1:10086/eureka